const pdfInput=document.getElementById('pdfFile'),xlsxInput=document.getElementById('xlsxFile'),prepare=document.getElementById('prepare'),status=document.getElementById('status'),templateBtn=document.getElementById('downloadTemplate');
let pdf=null,parsed=null;
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
const S=v=>v==null?'':String(v),T=v=>S(v).trim(),E=v=>S(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function reset(){for(const id of ['summary','fields','preview'])document.getElementById(id).hidden=true;document.getElementById('fieldList').innerHTML='';document.getElementById('previewTable').innerHTML='';}
function refresh(){prepare.disabled=!(pdf&&parsed?.ok);}
function parseExcel(book){const sh=book.Sheets[book.SheetNames[0]],m=XLSX.utils.sheet_to_json(sh,{header:1,defval:'',raw:true});if(m.length<2)throw Error('Нужны строки 1 и 2.');const h=m[0].map(S),r=m[1].map(S);let nc=h.findIndex(x=>['№','номер','номер строки'].includes(T(x).toLowerCase()));if(nc<0)nc=0;const width=Math.max(h.length,r.length,...m.slice(2).map(x=>x.length));const fields=[];for(let c=nc+1;c<width;c++)if(T(h[c]))fields.push({col:c,name:h[c],ref:r[c],used:0});if(!fields.length)throw Error('После колонки «№» нет названных переменных.');const used=[],variable=[],reserve=[];for(let rr=2;rr<m.length;rr++){const row=Array.from({length:width},(_,i)=>S(m[rr]?.[i])),vals=fields.map(f=>row[f.col]);if(!vals.some(v=>S(v).length))continue;const has=vals.some(v=>T(v).length),rec={no:used.length+1,values:vals};used.push(rec);(has?variable:reserve).push(rec);fields.forEach((f,i)=>{if(T(vals[i]))f.used++;});}return{ok:true,fields,used,variable,reserve};}
function renderExcel(p){document.getElementById('totalPrint').textContent=p.used.length;document.getElementById('variablePrint').textContent=p.variable.length;document.getElementById('reservePrint').textContent=p.reserve.length;document.getElementById('fieldCount').textContent=p.fields.length;document.getElementById('summary').hidden=false;document.getElementById('previewTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>№</th>${p.fields.map(f=>`<th>${E(f.name)}</th>`).join('')}</tr></thead><tbody>${p.used.slice(0,8).map(x=>`<tr><td class="row-no">${x.no}</td>${x.values.map(v=>`<td>${E(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;document.getElementById('preview').hidden=false;}
function makeLines(items){const groups=[];for(const i of items.filter(x=>x.str)){const z={t:i.str,x:+(i.transform?.[4]||0),y:+(i.transform?.[5]||0),w:+(i.width||0),h:+(i.height||Math.abs(i.transform?.[3]||0))};let g=groups.find(a=>Math.abs(a.y-z.y)<=2.5);if(!g){g={y:z.y,a:[]};groups.push(g);}g.a.push(z);}return groups.sort((a,b)=>b.y-a.y).map(g=>{g.a.sort((a,b)=>a.x-b.x);let s='';for(let i=0;i<g.a.length;i++){if(i){const p=g.a[i-1],q=g.a[i],gap=q.x-(p.x+p.w);if(gap>Math.max(1,q.h*.15)&&!/[\s(\[«]$/.test(s)&&!/^[,.;:!?%)\]}]/.test(q.t))s+=' ';}s+=g.a[i].t;}return{t:T(s)};});}
function occ(a,b){let n=0,p=0;while((p=a.indexOf(b,p))>=0){n++;p+=Math.max(1,b.length);}return n;}
async function analyze(file,fields){const doc=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,pages=[];for(let p=1;p<=doc.numPages;p++){const c=await(await doc.getPage(p)).getTextContent();pages.push({p,lines:makeLines(c.items)});}const same=new Map();fields.forEach(f=>{const ref=T(f.ref);if(ref){const a=same.get(ref)||[];a.push(f.name);same.set(ref,a);}});return fields.map(f=>{const ref=T(f.ref);if(!ref)return{...f,count:0,loc:[],state:'empty'};let n=0,loc=[];for(const pg of pages)for(const line of pg.lines){const c=occ(line.t,ref);if(c){n+=c;loc.push({p:pg.p,c});}}const duplicate=(same.get(ref)||[]).length>1;return{...f,count:n,loc,state:duplicate?'duplicate':n?'found':'not-found'};});}
async function run(){prepare.disabled=true;status.textContent='Анализирую весь PDF…';try{const a=await analyze(pdf,parsed.fields);document.getElementById('fieldList').innerHTML=a.map(f=>{const icon=f.state==='found'?'✓':f.state==='not-found'?'⚠':'⛔',msg=f.state==='found'?`Найдено совпадений: ${f.count}`:f.state==='not-found'?'Совпадений не найдено':'Эталон совпадает с другим полем';return`<div class="field-row ${f.state==='not-found'?'field-warning':''} ${f.state==='duplicate'?'field-error':''}"><div class="field-check">${icon}</div><div class="field-name">${E(f.name)}</div><div class="field-reference">Эталон: ${E(f.ref||'—')}</div><div class="field-meta"><b>${msg}</b><div class="locations">${f.loc.map(x=>`<span class="location">стр. ${x.p}${x.c>1?' ×'+x.c:''}</span>`).join('')}</div></div></div>`;}).join('');document.getElementById('fields').hidden=false;status.textContent=`PDF проверен: ${a.reduce((q,f)=>q+f.count,0)} совпадений.`;}catch(e){status.textContent='Ошибка анализа PDF: '+e.message;}finally{refresh();}}
async function downloadTemplate(){if(!window.ExcelJS){status.textContent='ExcelJS не загрузился. Обновите страницу.';return;}const wb=new ExcelJS.Workbook(),sh=wb.addWorksheet('Данные');
// Чистая рабочая область: показатели слева, данные начинаются с D. Технические колонки спрятаны.
sh.getRange('A1:B4').values=[['Показатель','Значение'],['Общий тираж',''],['С переменными данными',''],['Резерв без данных','']];
const headers=['№','Номер изделия','Фамилия','Имя','Отчество','Звание','Поле 7','Поле 8','Поле 9','Поле 10'];
sh.getRange('D1:M2').values=[headers,['ЭТАЛОН','529260704929','Иванов','Иван','Иванович','майор','','','','']];
for(let r=3;r<=1002;r++){
  // Сама нумерация смотрит на всю оставшуюся строку, поэтому пробел тоже считается заполнением.
  sh.getCell(r,4).value={formula:`IF(COUNTA(E${r}:XFD${r})>0,ROW()-2,"")`};
  // Вспомогательная проверка содержательных данных: пробелы не считаются данными.
  sh.getCell(r,16).value={formula:`IF(SUMPRODUCT(--(LEN(TRIM(E${r}:XFD${r}&""))>0))>0,1,0)`};
  for(let c=5;c<=13;c++)sh.getCell(r,c).value='';
}
sh.getCell('B2').value={formula:'=COUNT(D3:D1002)'};
sh.getCell('B3').value={formula:'=SUM(P3:P1002)'};
sh.getCell('B4').value={formula:'=B2-B3'};
const hf={fill:'#1F2937',font:{bold:true,color:'#FFFFFF'},horizontal_alignment:'center',vertical_alignment:'center',wrap_text:true},rf={fill:'#FFF2CC',font:{bold:true,italic:true,color:'#7C3AED'},horizontal_alignment:'center',vertical_alignment:'center',wrap_text:true};
sh.getRange('A1:B1').format=hf;sh.getRange('A2:B4').format={fill:'#F8FAFC',borders:{style:'continuous',color:'#D0D5DD'}};sh.getRange('A2:A4').format.font={bold:true};sh.getRange('D1:M1').format=hf;sh.getRange('D2:M2').format=rf;
[24,15,3,18,20,20,18,18,18,18,18,18,18,3,3,3].forEach((w,i)=>sh.getColumn(i+1).width=w);
sh.getColumn(16).hidden=true;
sh.freeze_panes.freeze_rows(2);sh.freeze_panes.freeze_columns(4);
const info=wb.addWorksheet('Инструкция');info.getRange('A1:B8').values=[['ШАБЛОН VDP PRO 1100',''],['Строка 1','Названия колонок. Колонка «№» обязательна; все названные столбцы справа от неё считаются переменными.'],['Строка 2','Эталонные значения для поиска в PDF.'],['Строки 3+','Любое значение или даже пробел нумерует строку и включает её в общий тираж.'],['Пустая строка','Если во всех переменных ячейках действительно ничего нет, строка не нумеруется и в тираж не входит.'],['Пустая ячейка','Поле не заменяется в этом экземпляре.'],['Только пробелы','Строка получает номер и считается резервом без содержательных переменных данных.'],['Количество столбцов','Можно добавлять любое количество названных переменных столбцов справа от «№». Программа читает фактически заполненную структуру шаблона.']];info.mergeCells('A1:B1');info.getRange('A1:B1').format=hf;info.getRange('A2:A8').format.font={bold:true};info.getRange('A1:B8').format.borders={style:'continuous',color:'#D0D5DD'};info.getRange('B2:B8').format.wrap_text=true;info.getColumn(1).width=24;info.getColumn(2).width=105;
const b=await wb.xlsx.writeBuffer(),blob=new Blob([b],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='VDP_PRO1100_template.xlsx';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
templateBtn.addEventListener('click',downloadTemplate);pdfInput.addEventListener('change',e=>{pdf=e.target.files[0]||null;document.getElementById('pdfName').textContent=pdf?pdf.name:'Файл не выбран';status.textContent=pdf?'PDF выбран. Загрузите Excel с данными.':'Выберите PDF и Excel.';reset();refresh();});xlsxInput.addEventListener('change',async e=>{const f=e.target.files[0]||null;document.getElementById('xlsxName').textContent=f?f.name:'Файл не выбран';parsed=null;reset();if(!f){refresh();return;}try{parsed=parseExcel(XLSX.read(await f.arrayBuffer(),{type:'array',raw:true}));renderExcel(parsed);status.textContent=`Excel проверен: тираж ${parsed.used.length}, с переменными данными ${parsed.variable.length}, резерв ${parsed.reserve.length}.`;}catch(err){status.textContent='Ошибка чтения Excel: '+err.message;}refresh();});prepare.addEventListener('click',run);refresh();
