const pdfInput=document.getElementById('pdfFile');
const xlsxInput=document.getElementById('xlsxFile');
const prepare=document.getElementById('prepare');
const status=document.getElementById('status');
const templateBtn=document.getElementById('downloadTemplate');
const fieldCountInput=document.getElementById('fieldCountInput');
let pdf=null,parsed=null;

pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
const S=v=>v==null?'':String(v),T=v=>S(v).trim(),E=v=>S(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function refresh(){prepare.disabled=!(pdf&&parsed?.ok)}
function reset(){for(const id of ['summary','fields','preview'])document.getElementById(id).hidden=true;document.getElementById('fieldList').innerHTML='';document.getElementById('previewTable').innerHTML=''}
function parseExcel(book){const sh=book.Sheets[book.SheetNames[0]],m=XLSX.utils.sheet_to_json(sh,{header:1,defval:'',raw:false});if(m.length<2)throw Error('Нужны строки 1 и 2.');const h=(m[0]||[]).map(S),r=(m[1]||[]).map(S);let nc=h.findIndex(x=>['№','номер','номер строки'].includes(T(x).toLowerCase()));if(nc<0)throw Error('Не найдена колонка «№».');const width=Math.max(h.length,r.length,...m.slice(2).map(x=>x.length));const fields=[];for(let c=nc+1;c<width;c++){const name=T(h[c]);if(!name||['__used_flag','__data_flag'].includes(name))continue;fields.push({col:c,name,ref:S(r[c])})}if(!fields.length)throw Error('После колонки «№» нет пользовательских переменных полей.');const used=[],variable=[],reserve=[];for(let rr=2;rr<m.length;rr++){const row=Array.from({length:width},(_,i)=>S(m[rr]?.[i])),vals=fields.map(f=>row[f.col]);if(!vals.some(v=>S(v).length>0))continue;const has=vals.some(v=>T(v).length),rec={no:used.length+1,values:vals};used.push(rec);(has?variable:reserve).push(rec)}return{ok:true,fields,used,variable,reserve}}
function renderExcel(p){document.getElementById('totalPrint').textContent=p.used.length.toLocaleString('ru-RU');document.getElementById('variablePrint').textContent=p.variable.length.toLocaleString('ru-RU');document.getElementById('reservePrint').textContent=p.reserve.length.toLocaleString('ru-RU');document.getElementById('fieldCount').textContent=p.fields.length.toLocaleString('ru-RU');document.getElementById('summary').hidden=false;const head='<th>№</th>'+p.fields.map(f=>`<th>${E(f.name)}</th>`).join('');const body=p.used.slice(0,8).map(x=>`<tr><td class="row-no">${x.no}</td>${x.values.map(v=>`<td>${E(v)}</td>`).join('')}</tr>`).join('');document.getElementById('previewTable').innerHTML=`<div class="table-wrap"><table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></div>`;document.getElementById('preview').hidden=false}
function makeLines(items){const g=[];for(const i of items.filter(x=>x.str)){const z={t:i.str,x:+(i.transform?.[4]||0),y:+(i.transform?.[5]||0),w:+(i.width||0),h:+(i.height||Math.abs(i.transform?.[3]||0))};let a=g.find(q=>Math.abs(q.y-z.y)<=2.5);if(!a){a={y:z.y,a:[]};g.push(a)}a.a.push(z)}return g.sort((a,b)=>b.y-a.y).map(a=>{a.a.sort((x,y)=>x.x-y.x);let s='';for(let i=0;i<a.a.length;i++){const q=a.a[i];if(i){const p=a.a[i-1],gap=q.x-(p.x+p.w);if(gap>Math.max(1,q.h*.15)&&!/[\s(\[«]$/.test(s)&&!/^[,.;:!?%)\]}]/.test(q.t))s+=' '}s+=q.t}return{t:T(s)}})}
function occ(a,b){let n=0,p=0;if(!b)return 0;while((p=a.indexOf(b,p))>=0){n++;p+=Math.max(1,b.length)}return n}
async function analyze(file,fields){const doc=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,pages=[];for(let p=1;p<=doc.numPages;p++){const c=await(await doc.getPage(p)).getTextContent();pages.push({p,lines:makeLines(c.items)})}const same=new Map();fields.forEach(f=>{const ref=T(f.ref);if(ref){const a=same.get(ref)||[];a.push(f.name);same.set(ref,a)}});return fields.map(f=>{const ref=T(f.ref);if(!ref)return{...f,count:0,loc:[],state:'empty'};let n=0,loc=[];for(const pg of pages)for(const line of pg.lines){const c=occ(line.t,ref);if(c){n+=c;loc.push({p:pg.p,c})}}const dup=(same.get(ref)||[]).length>1;return{...f,count:n,loc,state:dup?'duplicate':n?'found':'not-found'}})}
async function run(){prepare.disabled=true;status.textContent='Анализирую весь PDF…';try{const a=await analyze(pdf,parsed.fields);document.getElementById('fieldList').innerHTML=a.map(f=>{const icon=f.state==='found'?'✓':f.state==='not-found'?'⚠':f.state==='duplicate'?'⛔':'—';const msg=f.state==='found'?`Найдено совпадений: ${f.count}`:f.state==='not-found'?'Совпадений не найдено':f.state==='duplicate'?'Эталон совпадает с другим полем':'Эталон не задан';const loc=f.loc.map(x=>`<span class="location">стр. ${x.p}${x.c>1?' ×'+x.c:''}</span>`).join('');return`<div class="field-row ${f.state==='not-found'?'field-warning':''} ${f.state==='duplicate'?'field-error':''}"><div class="field-check">${icon}</div><div class="field-name">${E(f.name)}</div><div class="field-reference">Эталон: ${E(f.ref||'—')}</div><div class="field-meta"><b>${msg}</b><div class="locations">${loc}</div></div></div>`}).join('');document.getElementById('fields').hidden=false;const total=a.reduce((q,f)=>q+f.count,0),problems=a.filter(f=>['not-found','duplicate'].includes(f.state)).length;status.textContent=problems?`PDF проверен: ${total} совпадений. Требуют внимания: ${problems}.`:`PDF проверен: ${total} совпадений. Все эталонные значения найдены.`}catch(e){status.textContent='Ошибка анализа PDF: '+e.message}finally{refresh()}}
function col(n){let s='';while(n>0){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26)}return s}
function setTextCell(ws,addr,value=''){ws[addr]={t:'s',v:S(value),z:'@'}}
function buildTemplate(fieldCount,maxRows){const names=[],refs=[];for(let i=1;i<=fieldCount;i++){names.push(i===1?'Номер изделия':i===2?'Фамилия':i===3?'Имя':i===4?'Отчество':i===5?'Звание':`Поле ${i}`);refs.push(i===1?'529260704929':i===2?'Иванов':i===3?'Иван':i===4?'Иванович':i===5?'майор':'')}const firstVar=5,lastVar=firstVar+fieldCount-1,usedCol=lastVar+1,dataCol=lastVar+2,usedL=col(usedCol),dataL=col(dataCol),rows=[];for(let r=1;r<=maxRows;r++){const row=new Array(dataCol).fill('');if(r===1){row[0]='Показатель';row[1]='Значение';row[3]='№';names.forEach((n,i)=>row[4+i]=n);row[usedCol-1]='__used_flag';row[dataCol-1]='__data_flag'}else if(r===2){row[0]='Общий тираж';row[3]='ЭТАЛОН';refs.forEach((v,i)=>row[4+i]=v)}else if(r===3){row[0]='С переменными данными'}else if(r===4){row[0]='Резерв без данных'}rows.push(row)}const ws=XLSX.utils.aoa_to_sheet(rows);for(let r=2;r<=maxRows;r++){for(let c=firstVar;c<=lastVar;c++)setTextCell(ws,`${col(c)}${r}`,ws[`${col(c)}${r}`]?.v||'')}for(let r=3;r<=maxRows;r++){const parts=[],meaningful=[];for(let c=firstVar;c<=lastVar;c++){const l=col(c);parts.push(`${l}${r}<>\"\"`);meaningful.push(`LEN(TRIM(${l}${r}&\"\"))>0`)}ws[`${usedL}${r}`]={f:`IF(OR(${parts.join(',')}),1,0)`};ws[`${dataL}${r}`]={f:`IF(OR(${meaningful.join(',')}),1,0)`};ws[`D${r}`]={f:`IF(${usedL}${r}=1,SUM($${usedL}$3:${usedL}${r}),\"\")`}}
ws.B2={f:`SUM(${usedL}3:${usedL}${maxRows})`};ws.B3={f:`SUM(${dataL}3:${dataL}${maxRows})`};ws.B4={f:'B2-B3'};
ws['!cols']=[{wch:24},{wch:16},{wch:3},{wch:7}];for(let i=0;i<fieldCount;i++)ws['!cols'].push({wch:20});ws['!cols'].push({wch:3,hidden:true},{wch:3,hidden:true});ws['!freeze']={xSplit:4,ySplit:2};
const hdr={fill:{patternType:'solid',fgColor:{rgb:'1F2937'}},font:{bold:true,color:{rgb:'FFFFFF'}},alignment:{horizontal:'center',vertical:'center',wrap_text:true}};const ref={fill:{patternType:'solid',fgColor:{rgb:'FFF2CC'}},font:{bold:true,italic:true,color:{rgb:'7C3AED'}},alignment:{horizontal:'center',vertical:'center',wrap_text:true}};['A1','B1','D1'].concat(names.map((_,i)=>XLSX.utils.encode_cell({r:0,c:4+i}))).forEach(a=>{if(ws[a])ws[a].s=hdr});['D2'].concat(refs.map((_,i)=>XLSX.utils.encode_cell({r:1,c:4+i}))).forEach(a=>{if(ws[a]){ws[a].s=ref;ws[a].z='@';ws[a].t='s'}});['A2','A3','A4'].forEach(a=>{if(ws[a])ws[a].s={font:{bold:true}}});return ws}
function downloadTemplate(){try{if(!window.XLSX){status.textContent='Модуль Excel не загрузился. Нажмите Ctrl+F5.';return}let count=Number.parseInt(fieldCountInput?.value||'5',10);if(!Number.isFinite(count)||count<1)count=5;if(count>100)count=100;if(fieldCountInput)fieldCountInput.value=String(count);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,buildTemplate(count,1000),'Данные');const info=XLSX.utils.aoa_to_sheet([['ШАБЛОН ДАННЫХ VDP PRO 1100',''],['Строка 1','Названия колонок. Колонка № обязательна; переменные поля справа от неё.'],['Строка 2','ЭТАЛОННЫЕ значения для поиска по всему PDF.'],['Строки 3+','Все значения переменных полей вводятся и хранятся как текст. Любой символ, включая пробел, включает строку в общий тираж.'],['Пустая строка','Не нумеруется и не входит в тираж.'],['Только пробелы','Нумеруются и входят в общий тираж, но не считаются переменными данными.'],['Количество полей','Можно менять для каждого заказа.']]);info['!cols']=[{wch:28},{wch:100}];XLSX.utils.book_append_sheet(wb,info,'Инструкция');XLSX.writeFile(wb,'VDP_PRO1100_template.xlsx',{cellStyles:true});status.textContent='Шаблон Excel сформирован и скачан.'}catch(e){console.error(e);status.textContent='Ошибка создания шаблона Excel: '+e.message}}
templateBtn.addEventListener('click',downloadTemplate);pdfInput.addEventListener('change',e=>{pdf=e.target.files[0]||null;document.getElementById('pdfName').textContent=pdf?pdf.name:'Файл не выбран';status.textContent=pdf?'PDF выбран. Загрузите Excel с данными.':'Выберите PDF и Excel.';reset();refresh()});xlsxInput.addEventListener('change',async e=>{const f=e.target.files[0]||null;document.getElementById('xlsxName').textContent=f?f.name:'Файл не выбран';parsed=null;reset();if(!f){refresh();return}try{parsed=parseExcel(XLSX.read(await f.arrayBuffer(),{type:'array',raw:true}));renderExcel(parsed);status.textContent=`Excel проверен: тираж ${parsed.used.length}, с переменными данными ${parsed.variable.length}, резерв ${parsed.reserve.length}.`}catch(err){status.textContent='Ошибка чтения Excel: '+err.message}refresh()});prepare.addEventListener('click',run);refresh();