const pdfInput=document.getElementById('pdfFile');
const xlsxInput=document.getElementById('xlsxFile');
const prepareOld=document.getElementById('prepare');
const statusV6=document.getElementById('status');
let pdfV6=null, parsedV6=null, analysisV6=null;
const S6=v=>v==null?'':String(v);
const T6=v=>S6(v).trim();
const E6=v=>S6(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function setStatus6(text){if(statusV6)statusV6.textContent=text}
function parseExcelV6(book){const sh=book.Sheets[book.SheetNames[0]],m=XLSX.utils.sheet_to_json(sh,{header:1,defval:'',raw:false});if(m.length<2)throw Error('Нужны строки 1 и 2.');const h=(m[0]||[]).map(S6),refs=(m[1]||[]).map(S6);let nc=h.findIndex(x=>['№','номер','номер строки'].includes(T6(x).toLowerCase()));if(nc<0)throw Error('Не найдена колонка «№».');const width=Math.max(h.length,refs.length,...m.slice(2).map(x=>x.length));const fields=[];for(let c=nc+1;c<width;c++){const name=T6(h[c]);if(!name||['__used_flag','__data_flag'].includes(name))continue;fields.push({col:c,name,ref:S6(refs[c])})}if(!fields.length)throw Error('После колонки «№» нет пользовательских переменных полей.');const used=[],variable=[],reserve=[];for(let rr=2;rr<m.length;rr++){const row=Array.from({length:width},(_,i)=>S6(m[rr]?.[i])),vals=fields.map(f=>row[f.col]);if(!vals.some(v=>S6(v).length>0))continue;const meaningful=vals.some(v=>T6(v).length>0);const rec={no:used.length+1,values:vals};used.push(rec);(meaningful?variable:reserve).push(rec)}return{ok:true,fields,used,variable,reserve}}
function renderExcelV6(p){document.getElementById('totalPrint').textContent=p.used.length.toLocaleString('ru-RU');document.getElementById('variablePrint').textContent=p.variable.length.toLocaleString('ru-RU');document.getElementById('reservePrint').textContent=p.reserve.length.toLocaleString('ru-RU');document.getElementById('fieldCount').textContent=p.fields.length.toLocaleString('ru-RU');document.getElementById('summary').hidden=false;const head='<th>№</th>'+p.fields.map(f=>`<th>${E6(f.name)}</th>`).join('');const body=p.used.slice(0,8).map(x=>`<tr><td class="row-no">${x.no}</td>${x.values.map(v=>`<td>${E6(v)}</td>`).join('')}</tr>`).join('');document.getElementById('previewTable').innerHTML=`<div class="table-wrap"><table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></div>`;document.getElementById('preview').hidden=false}
function resetV6(){for(const id of ['summary','fields','preview','generation']){const el=document.getElementById(id);if(el)el.hidden=true}const fl=document.getElementById('fieldList');if(fl)fl.innerHTML='';const pv=document.getElementById('previewTable');if(pv)pv.innerHTML='';const gb=document.getElementById('generateVdp');if(gb)gb.disabled=true;analysisV6=null}
function makeLinesV6(items){const g=[];for(const i of items.filter(x=>x.str)){const z={t:i.str,x:+(i.transform?.[4]||0),y:+(i.transform?.[5]||0),w:+(i.width||0),h:+(i.height||Math.abs(i.transform?.[3]||0))};let a=g.find(q=>Math.abs(q.y-z.y)<=2.5);if(!a){a={y:z.y,a:[]};g.push(a)}a.a.push(z)}return g.sort((a,b)=>b.y-a.y).map(a=>{a.a.sort((x,y)=>x.x-y.x);let s='';for(let i=0;i<a.a.length;i++){const q=a.a[i];if(i){const p=a.a[i-1],gap=q.x-(p.x+p.w);if(gap>Math.max(1,q.h*.15)&&!/[\\s(\\[«]$/.test(s)&&!/^[,.;:!?%)\\]}]/.test(q.t))s+=' '}s+=q.t}return{t:T6(s)}})}
function occV6(a,b){let n=0,p=0;if(!b)return 0;while((p=a.indexOf(b,p))>=0){n++;p+=Math.max(1,b.length)}return n}
async function analyzeV6(file,fields){const doc=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,pages=[];for(let p=1;p<=doc.numPages;p++){const c=await(await doc.getPage(p)).getTextContent();pages.push({p,lines:makeLinesV6(c.items)})}const same=new Map();fields.forEach(f=>{const ref=T6(f.ref);if(ref){const a=same.get(ref)||[];a.push(f.name);same.set(ref,a)}});return fields.map(f=>{const ref=T6(f.ref);if(!ref)return{...f,count:0,loc:[],state:'empty'};let n=0,loc=[];for(const pg of pages)for(const line of pg.lines){const c=occV6(line.t,ref);if(c){n+=c;loc.push({p:pg.p,c})}}const dup=(same.get(ref)||[]).length>1;return{...f,count:n,loc,state:dup?'duplicate':n?'found':'not-found'}})}
function renderAnalysisV6(a){document.getElementById('fieldList').innerHTML=a.map(f=>{const icon=f.state==='found'?'✓':f.state==='not-found'?'⚠':f.state==='duplicate'?'⛔':'—';const msg=f.state==='found'?`Найдено совпадений: ${f.count}`:f.state==='not-found'?'Совпадений не найдено':f.state==='duplicate'?'Эталон совпадает с другим полем':'Эталон не задан';const loc=f.loc.map(x=>`<span class="location">стр. ${x.p}${x.c>1?' ×'+x.c:''}</span>`).join('');return `<div class="field-row ${f.state==='not-found'?'field-warning':''} ${f.state==='duplicate'?'field-error':''}"><div class="field-check">${icon}</div><div class="field-name">${E6(f.name)}</div><div class="field-reference">Эталон: ${E6(f.ref||'—')}</div><div class="field-meta"><b>${msg}</b><div class="locations">${loc}</div></div></div>`}).join('');document.getElementById('fields').hidden=false}
