(()=>{'use strict';
const pdfInput=document.getElementById('pdfFile'),xlsxInput=document.getElementById('xlsxFile'),prepareBtn=document.getElementById('prepare'),status=document.getElementById('status'),generation=document.getElementById('generation'),generateBtn=document.getElementById('generateVdp'),outputLink=document.getElementById('downloadVdp'),outputInfo=document.getElementById('generationInfo');
let pdfFile=null,parsed=null,busy=false,outputUrl=null,map=null;
const S=v=>v==null?'':String(v),T=v=>S(v).trim(),msg=t=>{if(status)status.textContent=t};
const setGen=ok=>{generation.hidden=!ok;generateBtn.disabled=!ok};
function parseExcel(book){const sh=book.Sheets[book.SheetNames[0]],m=XLSX.utils.sheet_to_json(sh,{header:1,defval:'',raw:false});if(m.length<2)throw Error('Нужны строки 1 и 2.');const h=(m[0]||[]).map(S),refs=(m[1]||[]).map(S),nc=h.findIndex(x=>['№','номер','номер строки','номер изделия'].includes(T(x).toLowerCase()));if(nc<0)throw Error('Не найдена колонка «№».');const width=Math.max(h.length,refs.length,...m.slice(2).map(r=>r.length)),fields=[];for(let c=nc+1;c<width;c++){const name=T(h[c]);if(!name||['__used_flag','__data_flag'].includes(name))continue;fields.push({col:c,name,ref:S(refs[c])})}if(!fields.length)throw Error('После «№» нет пользовательских полей.');const used=[],variable=[],reserve=[];for(let rr=2;rr<m.length;rr++){const row=Array.from({length:width},(_,i)=>S(m[rr]?.[i])),vals=fields.map(f=>row[f.col]);if(!vals.some(v=>v.length>0))continue;const rec={no:used.length+1,values:vals};used.push(rec);(vals.some(v=>T(v).length>0)?variable:reserve).push(rec)}return{fields,used,variable,reserve}}
function norm(s){return S(s).normalize('NFC')}
function lines(items){const out=[];for(const i of items.filter(x=>x.str)){out.push({t:i.str,x:+i.transform[4],y:+i.transform[5],w:+i.width||0,h:+i.height||Math.abs(i.transform[3]||0)})}return out}
function findPdfText(c,ref){const r=norm(T(ref));if(!r)return[];const a=lines(c.items),hits=[];for(let i=0;i<a.length;i++){const it=norm(a[i].t);let pos=it.indexOf(r);if(pos>=0)hits.push({page:c.pageIndex,kind:'text',x:a[i].x,y:a[i].y,w:a[i].w,h:a[i].h});}return hits}
async function analyze(file,fields){const doc=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,pages=[];for(let p=1;p<=doc.numPages;p++){const pg=await doc.getPage(p),c=await pg.getTextContent();pages.push({p,c})}const refSeen=new Map();for(const f of fields){const r=T(f.ref);if(!r)continue;const a=refSeen.get(norm(r))||[];a.push(f.name);refSeen.set(norm(r),a)}return fields.map(f=>{const ref=T(f.ref);if(!ref)return {...f,state:'empty',matches:[]};let matches=[];for(const pg of pages)for(const h of findPdfText({...pg.c,pageIndex:pg.p},ref))matches.push(h);const duplicate=(refSeen.get(norm(ref))||[]).length>1;return {...f,matches,state:duplicate?'duplicate':matches.length?'found':'not-found'}})}
function escXml(s){return S(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function escPdf(s){return S(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
async function mupdfDoc(){const b=new Uint8Array(await pdfFile.arrayBuffer()),m=await import('https://cdn.jsdelivr.net/npm/mupdf@1.28.0/dist/mupdf.js');return {m,source:m.Document.openDocument(b,'application/pdf')}}
function latin1(bytes){let s='';for(let i=0;i<bytes.length;i+=8192){let t='';for(let j=i;j<Math.min(bytes.length,i+8192);j++)t+=String.fromCharCode(bytes[j]);s+=t}return s}
function bytes(s){const a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i)&255;return a}
function literalTokens(body){const out=[];let i=0;while(i<body.length){if(body[i]!=='('){i++;continue}let j=i+1,b='';while(j<body.length){if(body[j]==='\\'&&j+1<body.length){b+=body[j]+body[j+1];j+=2;continue}if(body[j]===')')break;b+=body[j++]}if(j>=body.length)break;out.push({text:b});i=j+1}return out}
function replaceAscii(text,ref,val){let count=0;const re=/\[(.*?)\]\s*TJ/gs;const escR=escPdf(ref);text=text.replace(re,m=>{const body=m.slice(1,m.lastIndexOf(']')),tok=literalTokens(body);if(!tok.length)return m;const joined=tok.map(x=>x.text.replace(/\\([\\()])/g,'$1')).join(''),p=joined.indexOf(ref);if(p<0)return m;count++;return `[(${escPdf(joined.slice(0,p))})(${escPdf(val)})(${escPdf(joined.slice(p+ref.length))})]TJ`});const re2=new RegExp('\\('+escR+'\\)Tj','g');text=text.replace(re2,()=>{count++;return `(${escPdf(val)})Tj`});return {text,count}}
function contents(po){const c=po.get('Contents');if(!c)return[];if(c.isArray&&c.isArray()){const a=[];for(let i=0;i<c.length;i++)a.push(c.get(i));return a}return[c]}
function patchAscii(doc,page,reps){const po=page.getObject(),parts=contents(po);if(!parts.length)return 0;let all='',n=0;for(const st of parts){let t=latin1(st.readStream().asUint8Array());for(const r of reps){const z=replaceAscii(t,r.ref,r.value);t=z.text;n+=z.count}all+=(all?'\n':'')+t}if(n)po.put('Contents',doc.addStream(bytes(all),{}));return n}
async function makePagePdf(sourcePdf,m,pageNo,record,fields){const d=new m.PDFDocument(),src=sourcePdf.loadPage(pageNo),out=d.graftPage(-1,sourcePdf,pageNo),page=d.loadPage(0),reps=[];for(let i=0;i<fields.length;i++){const f=fields[i],v=S(record.values[i]);if(!T(f.ref)||!v)continue;const unicode=/[^\x20-\x7E]/.test(v)||/[^\x20-\x7E]/.test(f.ref);if(!unicode)reps.push({ref:T(f.ref),value:v,name:f.name})}if(reps.length)patchAscii(d,page,reps);page.destroy();src.destroy();return d.saveToBuffer('garbage,compress').asUint8Array()}
function md5(a){let h=0x811c9dc5;for(const b of a){h^=b;h=Math.imul(h,16777619)}return ('00000000'+(h>>>0).toString(16)).slice(-8)}
function ppmlXml(width,height,bgs,varFiles,records,pageCount){const x=['<?xml version="1.0" encoding="UTF-8"?>','<!DOCTYPE PPML PUBLIC "-//PODi//DTD PPML 2.20//EN" "http://www.podi.org/ppml/ppml220.dtd">',`<PPML Version="2.2" Creator="VDP PRO 1100" ResourcesIncluded="Yes">`];for(let p=1;p<=pageCount;p++){x.push(`<REUSABLE_OBJECT><OBJECT Position="0 0"><SOURCE Dimensions="${width} ${height}" Format="application/pdf"><EXTERNAL_DATA Src="${escXml(bgs[p])}"/></SOURCE></OBJECT><OCCURRENCE_LIST><OCCURRENCE Name="BG${p}" Scope="PPML" Weight="100"><VIEW/></OCCURRENCE></OCCURRENCE_LIST></REUSABLE_OBJECT>`)}x.push('<DOCUMENT_SET>');for(const r of records){x.push(`<DOCUMENT Label="Record ${r.no}" PageCount="${pageCount}">`);for(let p=1;p<=pageCount;p++){x.push(`<PAGE Label="R${r.no}P${p}"><PAGE_DESIGN TrimBox="0 0 ${width} ${height}"/><MARK Position="0 0"><OCCURRENCE_REF Ref="BG${p}"/></MARK>`);const vf=varFiles[`r${r.no}p${p}`];if(vf)x.push(`<MARK Position="0 0"><OBJECT Position="0 0"><SOURCE Dimensions="${width} ${height}" Format="application/pdf"><EXTERNAL_DATA Src="${escXml(vf)}" Checksum="${md5(vfBytes[vf])}" ChecksumType="MD5"/></SOURCE></OBJECT></MARK>`);x.push('</PAGE>')}x.push('</DOCUMENT>')}x.push('</DOCUMENT_SET></PPML>');return x.join('\n')}
let vfBytes={};
async function generatePPML(){if(typeof JSZip==='undefined')throw Error('ZIP-библиотека недоступна.');const {m,source}=await mupdfDoc(),ppc=source.countPages(),doc=source.asPDF(),zip=new JSZip(),bg={};try{const first=source.loadPage(0),rect=first.getBounds(),width=rect[2]-rect[0],height=rect[3]-rect[1];first.destroy();for(let p=0;p<ppc;p++){const one=new m.PDFDocument();one.graftPage(-1,doc,p);const b=one.saveToBuffer('garbage,compress').asUint8Array();const path=`backgrounds/bg_${String(p+1).padStart(2,'0')}.pdf`;zip.file(path,b);bg[p+1]=path;one.destroy()}
const vars={};for(const rec of parsed.used){for(let p=0;p<ppc;p++){const has=parsed.fields.some((f,i)=>{const v=S(rec.values[i]);return v.length>0&&T(f.ref)});if(!has)continue;const b=await makePagePdf(doc,m,p,rec,parsed.fields);const path=`variables/record_${String(rec.no).padStart(4,'0')}_page_${String(p+1).padStart(2,'0')}.pdf`;zip.file(path,b);vfBytes[path]=b;vars[`r${rec.no}p${p+1}`]=path}}const xml=ppmlXml(width,height,bg,vars,parsed.used,ppc);zip.file('VDP_PRO1100.ppml',xml);zip.file('VALIDATION.txt',`PPML 2.2\nTemplate pages: ${ppc}\nRecords: ${parsed.used.length}\nLogical pages: ${ppc*parsed.used.length}\nFields: ${parsed.fields.length}\nUnicode values: accepted in input; final DFE validation required.\n`);const blob=await zip.generateAsync({type:'blob'});return {blob,pages:ppc*parsed.used.length,fields:parsed.fields.length,records:parsed.used.length}}finally{source.destroy()}}
async function prepare(){try{const f=xlsxInput.files?.[0];if(!pdfFile||!f)return;parsed=parseExcel(XLSX.read(await f.arrayBuffer(),{type:'array',raw:false}));map=await analyze(pdfFile,parsed.fields);const bad=map.filter(x=>['not-found','duplicate'].includes(x.state));setGen(parsed.used.length>0&&bad.length===0&&map.some(x=>x.state==='found'));if(bad.length)msg(`Проверка: проблемы с эталонами (${bad.length}).`);else msg(`Проверка завершена: ${map.reduce((n,x)=>n+x.matches.length,0)} найденных мест, ${parsed.fields.length} полей.`)}catch(e){setGen(false);msg('Ошибка: '+e.message)}}
pdfInput?.addEventListener('change',e=>{pdfFile=e.target.files?.[0]||null;setGen(false)});xlsxInput?.addEventListener('change',()=>setGen(false));prepareBtn?.addEventListener('click',()=>setTimeout(prepare,0));generateBtn?.addEventListener('click',async()=>{if(busy)return;busy=true;generateBtn.disabled=true;try{const r=await generatePPML();outputUrl&&URL.revokeObjectURL(outputUrl);outputUrl=URL.createObjectURL(r.blob);outputLink.href=outputUrl;outputLink.download='VDP_PRO1100_job_ppml.zip';outputLink.hidden=false;outputInfo.textContent=`PPML готов: ${r.pages} логических страниц, ${r.records} записей, ${r.fields} полей. Внутри ZIP — VDP_PRO1100.ppml и PDF-ресурсы.`;msg(`PPML 2.2 создан: ${r.pages} логических страниц.`)}catch(e){msg('Ошибка PPML: '+e.message);outputInfo.textContent='Файл не создан.'}finally{busy=false;generateBtn.disabled=false}});
})();