(()=>{'use strict';
const pdfInput=document.getElementById('pdfFile'),xlsxInput=document.getElementById('xlsxFile'),prepareBtn=document.getElementById('prepare'),generation=document.getElementById('generation'),status=document.getElementById('status');
let pdfFile=null,parsed=null,mapping=null;
const S=v=>v==null?'':String(v),T=v=>S(v).trim(),msg=t=>{if(status)status.textContent=t};
function parseExcel(book){const sh=book.Sheets[book.SheetNames[0]],m=XLSX.utils.sheet_to_json(sh,{header:1,defval:'',raw:false});if(m.length<2)throw Error('Нужны строки 1 и 2.');const h=(m[0]||[]).map(S),refs=(m[1]||[]).map(S),nc=h.findIndex(x=>['№','номер','номер строки','номер изделия'].includes(T(x).toLowerCase()));if(nc<0)throw Error('Не найдена колонка «№».');const width=Math.max(h.length,refs.length,...m.slice(2).map(r=>r.length)),fields=[];for(let c=nc+1;c<width;c++){const name=T(h[c]);if(!name||['__used_flag','__data_flag'].includes(name))continue;fields.push({col:c,name,ref:S(refs[c])})}if(!fields.length)throw Error('После «№» нет пользовательских полей.');const used=[],variable=[],reserve=[];for(let rr=2;rr<m.length;rr++){const row=Array.from({length:width},(_,i)=>S(m[rr]?.[i])),vals=fields.map(f=>row[f.col]);if(!vals.some(v=>v.length>0))continue;const rec={no:used.length+1,values:vals};used.push(rec);(vals.some(v=>T(v).length>0)?variable:reserve).push(rec)}return{fields,used,variable,reserve}}
function norm(s){return S(s).normalize('NFC')}
function rectOf(h){return {x:Math.min(h[0],h[2],h[4],h[6]),y:Math.min(h[1],h[3],h[5],h[7]),w:Math.max(h[0],h[2],h[4],h[6])-Math.min(h[0],h[2],h[4],h[6]),h:Math.max(h[1],h[3],h[5],h[7])-Math.min(h[1],h[3],h[5],h[7])}}
async function analyze(file,fields){const doc=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,pages=[];for(let p=1;p<=doc.numPages;p++){const pg=await doc.getPage(p),c=await pg.getTextContent();pages.push({p,c})}const usedRefs=new Map();for(const f of fields){const r=T(f.ref);if(r){const a=usedRefs.get(norm(r))||[];a.push(f.name);usedRefs.set(norm(r),a)}}return fields.map(f=>{const ref=T(f.ref);if(!ref)return{...f,state:'empty',matches:[]};const matches=[];for(const pg of pages){const items=pg.c.items.filter(x=>x.str);for(const it of items){if(norm(it.str).includes(norm(ref)))matches.push({page:pg.p,rect:{x:+it.transform[4],y:+it.transform[5],w:+it.width||0,h:+it.height||Math.abs(it.transform[3]||0)}})}}const duplicate=(usedRefs.get(norm(ref))||[]).length>1;return{...f,state:duplicate?'duplicate':matches.length?'found':'not-found',matches}})}
function latin1(bytes){let s='';for(let i=0;i<bytes.length;i+=8192){let t='';for(let j=i;j<Math.min(bytes.length,i+8192);j++)t+=String.fromCharCode(bytes[j]);s+=t}return s}
function toBytes(s){const a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i)&255;return a}
function escPdf(s){return S(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function literalTokens(body){const out=[];let i=0;while(i<body.length){if(body[i]!=='('){i++;continue}let j=i+1,b='';while(j<body.length){if(body[j]==='\\'&&j+1<body.length){b+=body[j]+body[j+1];j+=2;continue}if(body[j]===')')break;b+=body[j++]}if(j>=body.length)break;out.push(b);i=j+1}return out}
function patchAscii(doc,page,reps){const po=page.getObject(),c=po.get('Contents');if(!c)return 0;const parts=c.isArray&&c.isArray()?[...Array(c.length)].map((_,i)=>c.get(i)):[c];let total=0,all='';for(const st of parts){let text=latin1(st.readStream().asUint8Array());for(const rep of reps){const re=/\[(.*?)\]\s*TJ/gs;text=text.replace(re,m=>{const body=m.slice(1,m.lastIndexOf(']')),tok=literalTokens(body),joined=tok.map(x=>x.replace(/\\([\\()])/g,'$1')).join(''),p=joined.indexOf(rep.ref);if(p<0)return m;total++;return `[(${escPdf(joined.slice(0,p))})(${escPdf(rep.value)})(${escPdf(joined.slice(p+rep.ref.length))})]TJ`});const re2=new RegExp('\\('+escPdf(rep.ref)+'\\)Tj','g');text=text.replace(re2,()=>{total++;return `(${escPdf(rep.value)})Tj`})}all+=(all?'\n':'')+text}if(total)po.put('Contents',doc.addStream(toBytes(all),{}));return total}
function addFontResource(doc,page,fontRes){const po=page.getObject();let rs=po.get('Resources');if(!rs||!rs.isDictionary()){rs=doc.newDictionary();po.put('Resources',rs)}let fonts=rs.get('Font');if(!fonts||!fonts.isDictionary()){fonts=doc.newDictionary();rs.put('Font',fonts)}fonts.put('FVDP',fontRes)}
function glyphHex(font,text){let out='';for(const ch of Array.from(norm(text))){const gid=font.encodeCharacter(ch.codePointAt(0));if(!gid)throw Error(`Шрифт не содержит «${ch}».`);out+=gid.toString(16).padStart(4,'0')}return out}
function putUnicode(doc,page,font,fontRes,text,rect){const size=Math.max(4,rect.h*0.9),baseline=rect.y+rect.h-size*0.18,pageH=page.getBounds()[3],hex=glyphHex(font,text);addFontResource(doc,page,fontRes);const c=`q 1 0 0 -1 0 ${pageH} cm BT /FVDP ${size} Tf 1 0 0 1 ${rect.x} ${baseline} Tm <${hex}> Tj ET Q`;const st=doc.addStream(c,{}),po=page.getObject(),cur=po.get('Contents');if(!cur||cur.isNull())po.put('Contents',st);else{const a=doc.newArray();if(cur.isArray())for(let i=0;i<cur.length;i++)a.push(cur.get(i));else a.push(cur);a.push(st);po.put('Contents',a)}}
function patchUnicode(doc,page,reps,font,fontRes){const hits=[];for(const rep of reps){const qs=page.search(rep.ref,500)||[];for(const q of qs){const r=rectOf(q);hits.push({rep,rect:{x:r.x-0.35,y:r.y-0.25,w:r.w+0.7,h:r.h+0.5}})}}if(!hits.length)return 0;for(const h of hits)page.addRedaction({x:h.rect.x,y:h.rect.y,width:h.rect.w,height:h.rect.h});page.applyRedactions(false,0,0,0);for(const h of hits)putUnicode(doc,page,font,fontRes,h.rep.value,h.rect);return hits.length}
async function fontBytes(){const r=await fetch('https://cdn.jsdelivr.net/npm/dejavu-fonts-ttf@2.37.3/ttf/DejaVuSans.ttf',{cache:'force-cache'});if(!r.ok)throw Error('Не удалось загрузить Unicode-шрифт.');return new Uint8Array(await r.arrayBuffer())}
async function onePage(m,srcDoc,pageNo,recs,fields,font,fontRes){const d=new m.PDFDocument();d.graftPage(-1,srcDoc,pageNo);const page=d.loadPage(0),ascii=[],unicode=[];for(let i=0;i<fields.length;i++){const f=fields[i],v=S(recs.values[i]);if(!T(f.ref)||v.length===0)continue;const uni=/[^\x20-\x7E]/.test(v)||/[^\x20-\x7E]/.test(f.ref);(uni?unicode:ascii).push({name:f.name,ref:T(f.ref),value:v})}if(ascii.length)patchAscii(d,page,ascii);if(unicode.length)patchUnicode(d,page,unicode,font,fontRes);const b=d.saveToBuffer('garbage,compress').asUint8Array();page.destroy();return b}
function xmlEsc(s){return S(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function buildXml(w,h,pageCount,records,files,fieldsCount){const x=[`<?xml version="1.0" encoding="UTF-8"?>`,`<!DOCTYPE PPML PUBLIC "-//PODi//DTD PPML 2.20//EN" "http://www.podi.org/ppml/ppml220.dtd">`,`<PPML Version="2.2" Creator="VDP PRO 1100" ResourcesIncluded="Yes">`];for(let p=1;p<=pageCount;p++)x.push(`<REUSABLE_OBJECT><OBJECT Position="0 0"><SOURCE Dimensions="${w} ${h}" Format="application/pdf"><EXTERNAL_DATA Src="backgrounds/bg_${String(p).padStart(2,'0')}.pdf"/></SOURCE></OBJECT><OCCURRENCE_LIST><OCCURRENCE Name="BG${p}" Scope="PPML" Weight="100"><VIEW/></OCCURRENCE></OCCURRENCE_LIST></REUSABLE_OBJECT>`);x.push('<DOCUMENT_SET>');for(const r of records){x.push(`<DOCUMENT Label="Record ${r.no}" PageCount="${pageCount}">`);for(let p=1;p<=pageCount;p++){const key=`r${r.no}p${p}`;x.push(`<PAGE Label="R${r.no}P${p}"><PAGE_DESIGN TrimBox="0 0 ${w} ${h}"/>`);if(files[key])x.push(`<MARK Position="0 0"><OBJECT Position="0 0"><SOURCE Dimensions="${w} ${h}" Format="application/pdf"><EXTERNAL_DATA Src="${xmlEsc(files[key])}"/></SOURCE></OBJECT></MARK>`);else x.push(`<MARK Position="0 0"><OCCURRENCE_REF Ref="BG${p}"/></MARK>`);x.push('</PAGE>')}x.push('</DOCUMENT>')}x.push('</DOCUMENT_SET></PPML>');return x.join('\n')}
async function generate(){if(!parsed)throw Error('Сначала проверьте PDF и Excel.');const {m,source}=await (async()=>{const b=new Uint8Array(await pdfFile.arrayBuffer()),m=await import('https://cdn.jsdelivr.net/npm/mupdf@1.28.0/dist/mupdf.js');return {m,source:m.Document.openDocument(b,'application/pdf')}})();const srcPdf=source.asPDF(),n=source.countPages();const first=source.loadPage(0),bb=first.getBounds(),w=bb[2]-bb[0],h=bb[3]-bb[1];first.destroy();const zip=new JSZip(),bgFiles={},modFiles={};const fontData=await fontBytes(),font=new m.Font('DejaVu Sans VDP',fontData),fontRes=null;try{for(let p=0;p<n;p++){const d=new m.PDFDocument();d.graftPage(-1,srcPdf,p);const b=d.saveToBuffer('garbage,compress').asUint8Array();const path=`backgrounds/bg_${String(p+1).padStart(2,'0')}.pdf`;zip.file(path,b);bgFiles[p+1]=path;d.destroy()}
for(const r of parsed.used){for(let p=1;p<=n;p++){const pageFields=parsed.fields.filter((f,i)=>{const v=S(r.values[i]);return v.length>0&&T(f.ref)&&mapping.find(x=>x.name===f.name)?.matches.some(h=>h.page===p)});if(!pageFields.length)continue;const fontDoc=new m.PDFDocument();const localFont=new m.Font('DejaVu Sans VDP',fontData),localRes=fontDoc.addFont(localFont);fontDoc.graftPage(-1,srcPdf,p-1);const page=fontDoc.loadPage(0);const ascii=[],unicode=[];for(const f of pageFields){const i=parsed.fields.findIndex(x=>x.name===f.name),v=S(r.values[i]);const uni=/[^\x20-\x7E]/.test(v)||/[^\x20-\x7E]/.test(f.ref);(uni?unicode:ascii).push({name:f.name,ref:T(f.ref),value:v})}if(ascii.length)patchAscii(fontDoc,page,ascii);if(unicode.length)patchUnicode(fontDoc,page,unicode,localFont,localRes);const b=fontDoc.saveToBuffer('garbage,compress').asUint8Array();const path=`variables/record_${String(r.no).padStart(4,'0')}_page_${String(p).padStart(2,'0')}.pdf`;zip.file(path,b);modFiles[`r${r.no}p${p}`]=path;page.destroy()}
}
const xml=buildXml(w,h,n,parsed.used,modFiles,parsed.fields.length);zip.file('VDP_PRO1100.ppml',xml);zip.file('VALIDATION.txt',`PPML 2.2\nTemplate pages: ${n}\nRecords: ${parsed.used.length}\nLogical pages: ${n*parsed.used.length}\nFields: ${parsed.fields.length}\nModified pages: ${Object.keys(modFiles).length}\n`;const blob=await zip.generateAsync({type:'blob'});return{blob,pages:n*parsed.used.length,records:parsed.used.length,fields:parsed.fields.length}}finally{source.destroy()}}
function addButton(){if(document.getElementById('generatePpml'))return;const host=generation||prepareBtn?.parentElement;if(!host)return;const b=document.createElement('button');b.id='generatePpml';b.type='button';b.disabled=true;b.textContent='СОЗДАТЬ PPML 2.2';b.style.marginTop='10px';const out=document.createElement('a');out.id='downloadPpml';out.className='secondary-btn';out.hidden=true;out.textContent='СКАЧАТЬ PPML 2.2 ZIP';out.style.marginTop='10px';const info=document.createElement('div');info.id='ppmlInfo';info.className='status';host.appendChild(b);host.appendChild(info);host.appendChild(out);b.addEventListener('click',async()=>{b.disabled=true;try{const r=await generate();out.href=URL.createObjectURL(r.blob);out.download='VDP_PRO1100_job_ppml.zip';out.hidden=false;info.textContent=`PPML готов: ${r.pages} логических страниц, ${r.records} записей, ${r.fields} полей.`}catch(e){info.textContent='Ошибка PPML: '+e.message}finally{b.disabled=false}});window.__enablePpml=()=>b.disabled=false}
addButton();pdfInput?.addEventListener('change',e=>pdfFile=e.target.files?.[0]||null);xlsxInput?.addEventListener('change',()=>{mapping=null});prepareBtn?.addEventListener('click',async()=>{setTimeout(async()=>{try{const f=xlsxInput.files?.[0];if(!pdfFile||!f)return;parsed=parseExcel(XLSX.read(await f.arrayBuffer(),{type:'array',raw:false}));mapping=await analyze(pdfFile,parsed.fields);const bad=mapping.filter(x=>['not-found','duplicate'].includes(x.state));if(bad.length){if(window.__enablePpml){}msg(`PDF проверен: есть проблемы (${bad.length}). PPML заблокирован.`);return}if(window.__enablePpml)window.__enablePpml();}catch(e){msg('Ошибка PPML-подготовки: '+e.message)}},250)});
})();