(()=>{'use strict';
const pdfInput=document.getElementById('pdfFile'),xlsxInput=document.getElementById('xlsxFile'),prepareBtn=document.getElementById('prepare'),status=document.getElementById('status'),generation=document.getElementById('generation'),generateBtn=document.getElementById('generateVdp'),outputLink=document.getElementById('downloadVdp'),outputInfo=document.getElementById('generationInfo');
let pdfFile=null,parsed=null,busy=false,outputUrl=null;
const S=v=>v==null?'':String(v),T=v=>S(v).trim(),msg=t=>{if(status)status.textContent=t};
function clearOutput(){if(outputUrl){URL.revokeObjectURL(outputUrl);outputUrl=null}if(outputLink){outputLink.hidden=true;outputLink.removeAttribute('href')}if(outputInfo)outputInfo.textContent=''}
function setGeneration(ok){if(generation)generation.hidden=!ok;if(generateBtn)generateBtn.disabled=!ok}
function parseExcel(book){const sh=book.Sheets[book.SheetNames[0]],m=XLSX.utils.sheet_to_json(sh,{header:1,defval:'',raw:false});if(m.length<2)throw Error('Нужны строки 1 и 2.');const h=(m[0]||[]).map(S),refs=(m[1]||[]).map(S),nc=h.findIndex(x=>['№','номер','номер строки','номер изделия'].includes(T(x).toLowerCase()));if(nc<0)throw Error('Не найдена колонка «№».');const width=Math.max(h.length,refs.length,...m.slice(2).map(r=>r.length)),fields=[];for(let c=nc+1;c<width;c++){const name=T(h[c]);if(!name||['__used_flag','__data_flag'].includes(name))continue;fields.push({col:c,name,ref:S(refs[c])})}if(!fields.length)throw Error('После колонки «№» нет пользовательских переменных полей.');const used=[],variable=[],reserve=[];for(let rr=2;rr<m.length;rr++){const row=Array.from({length:width},(_,i)=>S(m[rr]?.[i])),vals=fields.map(f=>row[f.col]);if(!vals.some(v=>S(v).length>0))continue;const meaningful=vals.some(v=>T(v).length>0),rec={no:used.length+1,values:vals};used.push(rec);(meaningful?variable:reserve).push(rec)}return{fields,used,variable,reserve}}
function makeLines(items){const gs=[];for(const i of items.filter(x=>x.str)){const z={t:i.str,x:+(i.transform?.[4]||0),y:+(i.transform?.[5]||0),w:+(i.width||0),h:+(i.height||Math.abs(i.transform?.[3]||0))};let g=gs.find(q=>Math.abs(q.y-z.y)<=2.5);if(!g){g={y:z.y,a:[]};gs.push(g)}g.a.push(z)}return gs.sort((a,b)=>b.y-a.y).map(g=>{g.a.sort((a,b)=>a.x-b.x);let s='';for(let i=0;i<g.a.length;i++){const q=g.a[i];if(i){const p=g.a[i-1],gap=q.x-(p.x+p.w);if(gap>Math.max(1,q.h*.15)&&!/[\s(\[«]$/.test(s)&&!/^[,.;:!?%)\]}]/.test(q.t))s+=' '}s+=q.t}return{t:T(s)}})}
function occ(a,b){let n=0,p=0;if(!b)return 0;while((p=a.indexOf(b,p))>=0){n++;p+=Math.max(1,b.length)}return n}
async function analyzePdf(file,fields){const doc=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,pages=[];for(let p=1;p<=doc.numPages;p++){const c=await(await doc.getPage(p)).getTextContent();pages.push({p,lines:makeLines(c.items)})}const same=new Map();for(const f of fields){const r=T(f.ref);if(r){const a=same.get(r)||[];a.push(f.name);same.set(r,a)}}return fields.map(f=>{const r=T(f.ref);if(!r)return{...f,count:0,loc:[],state:'empty'};let n=0,loc=[];for(const pg of pages)for(const l of pg.lines){const c=occ(l.t,r);if(c){n+=c;loc.push({p:pg.p,c})}}return{...f,count:n,loc,state:(same.get(r)||[]).length>1?'duplicate':n?'found':'not-found'}})}
function latin1(bytes){let s='';const chunk=8192;for(let i=0;i<bytes.length;i+=chunk){let t='';for(let j=i;j<Math.min(bytes.length,i+chunk);j++)t+=String.fromCharCode(bytes[j]);s+=t}return s}
function toBytes(s){const out=new Uint8Array(s.length);for(let i=0;i<s.length;i++)out[i]=s.charCodeAt(i)&255;return out}
function escPdf(s){return S(s).replaceAll('\\','\\\\').replaceAll('(','\\(').replaceAll(')','\\)')}
function literalTokens(body){const out=[];let i=0;while(i<body.length){if(body[i]!=='('){i++;continue}const start=i;let j=i+1,buf='';while(j<body.length){if(body[j]==='\\'&&j+1<body.length){buf+=body[j]+body[j+1];j+=2;continue}if(body[j]===')')break;buf+=body[j];j++}if(j>=body.length)break;out.push({start,end:j+1,text:buf});i=j+1}return out}
function decodeLiteral(s){return s.replace(/\\([\\()])/g,'$1')}
function replaceInTjArrays(text,ref,val){if(!ref)return{text,count:0};const re=/\[(.*?)\]\s*TJ/gs;let changed=0;const out=text.replace(re,m=>{const body=m.slice(1,m.lastIndexOf(']')),tokens=literalTokens(body);if(!tokens.length)return m;const combined=tokens.map(t=>decodeLiteral(t.text)).join('');const pos=combined.indexOf(ref);if(pos<0)return m;const end=pos+ref.length;const pre=combined.slice(0,pos),post=combined.slice(end);changed++;if(pre||post)return `[(${escPdf(pre)})(${escPdf(val)})(${escPdf(post)})]TJ`;return `[(${escPdf(val)})]TJ`});return{text:out,count:changed}}
function replaceDirectTj(text,ref,val){if(!ref)return{text,count:0};const a=escPdf(ref),b=escPdf(val);let count=0;const re=new RegExp('\\('+a+'\\)Tj','g');const out=text.replace(re,()=>{count++;return `(${b})Tj`});return{text:out,count}}
function contents(pageObj){const c=pageObj.get('Contents');if(!c)return[];if(c.isArray&&c.isArray()){const a=[];for(let i=0;i<c.length;i++){const o=c.get(i);if(o)a.push(o)}return a}return[c]}
function patchPage(doc,page,reps){const pageObj=page.getObject(),parts=contents(pageObj);if(!parts.length)return 0;let total=0,combined='';for(const stream of parts){let text=latin1(stream.readStream().asUint8Array());for(const rep of reps){const v=S(rep.value);if(!/^[\x20-\x7E]*$/.test(v))throw Error(`Поле «${rep.name}»: значение содержит Unicode. Для кириллицы будет отдельный режим шрифтовой замены.`);let a=replaceInTjArrays(text,rep.ref,v);text=a.text;total+=a.count;let b=replaceDirectTj(text,rep.ref,v);text=b.text;total+=b.count}if(combined)combined+='\n';combined+=text}if(total){const newStream=doc.addStream(toBytes(combined),{});pageObj.put('Contents',newStream)}return total}
async function generatePdf(){const srcBytes=new Uint8Array(await pdfFile.arrayBuffer()),mupdf=await import('https://cdn.jsdelivr.net/npm/mupdf@1.28.0/dist/mupdf.js'),source=mupdf.Document.openDocument(srcBytes,'application/pdf'),srcPdf=source.asPDF(),out=new mupdf.PDFDocument(),ppc=source.countPages();try{for(const rec of parsed.used){for(let p=0;p<ppc;p++){out.graftPage(-1,srcPdf,p);const page=out.loadPage(out.countPages()-1),reps=[];for(let i=0;i<parsed.fields.length;i++){const f=parsed.fields[i],raw=S(rec.values[i]);if(!T(f.ref)||raw.length===0)continue;reps.push({name:f.name,ref:T(f.ref),value:raw})}if(reps.length)patchPage(out,page,reps);page.destroy()}msg(`Создание VDP PDF: ${rec.no} из ${parsed.used.length}...`)}return{bytes:out.saveToBuffer('garbage,compress').asUint8Array(),pagesPerCopy:ppc}}finally{source.destroy()}}
async function verify(buf,ppc){const doc=await pdfjsLib.getDocument({data:buf}).promise;if(doc.numPages!==parsed.used.length*ppc)throw Error(`Ожидалось ${parsed.used.length*ppc} страниц, получено ${doc.numPages}.`);const pages=[];for(let p=1;p<=doc.numPages;p++){const c=await(await doc.getPage(p)).getTextContent();pages.push(makeLines(c.items).map(x=>x.t).join('\n'))}for(let r=0;r<parsed.used.length;r++){const block=pages.slice(r*ppc,(r+1)*ppc).join('\n');for(let i=0;i<parsed.fields.length;i++){const raw=S(parsed.used[r].values[i]),val=T(raw);if(!val)continue;if(!occ(block,val))throw Error(`Контроль экземпляра ${r+1}: не найдено значение «${val}».`)}}return doc.numPages}
async function prepare(){try{const f=xlsxInput.files?.[0];if(!pdfFile||!f)return;clearOutput();parsed=parseExcel(XLSX.read(await f.arrayBuffer(),{type:'array',raw:false}));const analysis=await analyzePdf(pdfFile,parsed.fields),bad=analysis.filter(a=>['not-found','duplicate'].includes(a.state));setGeneration(parsed.used.length>0&&!bad.length&&analysis.some(a=>a.state==='found'));if(bad.length)msg(`PDF проверен: есть проблемы с эталонами (${bad.length}).`);else msg(`PDF проверен: ${analysis.reduce((n,a)=>n+a.count,0)} совпадений. Все эталонные значения найдены.`)}catch(e){setGeneration(false);msg('Ошибка подготовки: '+e.message)}}
pdfInput?.addEventListener('change',e=>{pdfFile=e.target.files?.[0]||null;clearOutput();setGeneration(false)});xlsxInput?.addEventListener('change',()=>{clearOutput();setGeneration(false)});prepareBtn?.addEventListener('click',()=>setTimeout(prepare,0));generateBtn?.addEventListener('click',async()=>{if(busy)return;busy=true;generateBtn.disabled=true;try{const out=await generatePdf(),pages=await verify(out.bytes,out.pagesPerCopy),blob=new Blob([out.bytes],{type:'application/pdf'});outputUrl=URL.createObjectURL(blob);outputLink.href=outputUrl;outputLink.download='VDP_PRO1100_output.pdf';outputLink.hidden=false;outputInfo.textContent=`Готово. Проверено страниц: ${pages}.`;msg(`VDP PDF создан и проверен: ${pages} страниц.`)}catch(e){msg('Ошибка создания VDP PDF: '+e.message);outputInfo.textContent='Файл не создан.'}finally{busy=false;generateBtn.disabled=false}});})();